"""Generate pixel-accuracy fixtures for the JS renderers.

For each game it writes, under reference/<game>/:
  <n>.json  the raw state fields the JS renderer consumes (board, color, env_id)
  <n>.svg   pgx's own SVG for that exact state (the ground truth)

It also (re)generates assets/js/mcts/chess_pieces.mjs by base64-encoding pgx's
bundled chess piece SVGs, so the JS chess renderer embeds byte-identical art.

Run:  uv run python generate_reference.py
"""

import base64
import json
import os

import jax
import jax.numpy as jnp
import pgx
from pgx._src.visualizer import Visualizer

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SITE_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
REFERENCE_DIR = os.path.join(SCRIPT_DIR, "reference")

PGX_CHESS_IMAGES = os.path.join(
    os.path.dirname(pgx.__file__), "_src", "dwg", "images", "chess"
)
# token used by pgx's chess renderer -> its asset filename
PIECE_FILENAMES = {
    "wP": "wPawn", "wN": "wKnight", "wB": "wBishop",
    "wR": "wRook", "wQ": "wQueen", "wK": "wKing",
    "P": "bPawn", "N": "bKnight", "B": "bBishop",
    "R": "bRook", "Q": "bQueen", "K": "bKing",
}


def pgx_reference_svg(state):
    # color_theme="light" matches what we render on the (light) site card
    return Visualizer(color_theme="light").get_dwg(states=state).tostring()


def state_to_record(state):
    record = {"env_id": state.env_id,
              "board": [int(value) for value in state._x.board.reshape(-1)]}
    if hasattr(state._x, "color"):
        record["color"] = int(state._x.color)
    return record


def roll_out_states(env_id, seed, move_counts):
    """Roll out random legal moves; return states at the requested move counts."""
    environment = pgx.make(env_id)
    step = jax.jit(environment.step)
    key = jax.random.PRNGKey(seed)
    key, subkey = jax.random.split(key)
    state = environment.init(subkey)
    states = [state]
    for _ in range(max(move_counts)):
        if bool(state.terminated | state.truncated):
            break
        key, subkey = jax.random.split(key)
        legal_actions = jnp.where(state.legal_action_mask)[0]
        action = legal_actions[jax.random.randint(subkey, (), 0, legal_actions.shape[0])]
        state = step(state, action)
        states.append(state)
    return [states[min(count, len(states) - 1)] for count in move_counts]


def write_fixtures(game, states):
    directory = os.path.join(REFERENCE_DIR, game)
    os.makedirs(directory, exist_ok=True)
    board_length = 0
    for index, state in enumerate(states):
        record = state_to_record(state)
        board_length = len(record["board"])
        with open(os.path.join(directory, f"{index}.json"), "w") as file:
            json.dump(record, file)
        with open(os.path.join(directory, f"{index}.svg"), "w") as file:
            file.write(pgx_reference_svg(state))
    print(f"  {game}: {len(states)} states (board len {board_length})")


def generate_chess_pieces():
    entries = []
    for token, filename in PIECE_FILENAMES.items():
        with open(os.path.join(PGX_CHESS_IMAGES, f"{filename}.svg"), "rb") as file:
            base64_data = base64.b64encode(file.read()).decode("ascii")
        entries.append(f'  {json.dumps(token)}: "data:image/svg+xml;base64,{base64_data}",')
    body = "\n".join(entries)
    output_path = os.path.join(SITE_ROOT, "assets", "js", "mcts", "chess_pieces.mjs")
    with open(output_path, "w") as file:
        file.write(
            "// Auto-generated by tools/whlo/generate_reference.py from pgx's\n"
            "// bundled chess piece SVGs (Cburnett set). Do not edit by hand.\n"
            "export const CHESS_PIECES = {\n" + body + "\n};\n"
        )
    print(f"  wrote chess_pieces.mjs ({len(PIECE_FILENAMES)} pieces)")


def main():
    os.makedirs(REFERENCE_DIR, exist_ok=True)
    print("generating reference fixtures:")
    write_fixtures("tic_tac_toe", roll_out_states("tic_tac_toe", 0, [0, 3, 5, 7]))
    write_fixtures("connect_four", roll_out_states("connect_four", 1, [0, 4, 10, 20]))
    # chess: include odd move counts so a black-to-move (flipped) state is covered
    write_fixtures("chess", roll_out_states("chess", 2, [0, 1, 4, 7]))
    generate_chess_pieces()
    print("done ->", REFERENCE_DIR)


if __name__ == "__main__":
    main()
