"""Generate pixel-accuracy fixtures for the JS renderers.

For each game it writes, under web/reference/<game>/:
  <n>.json  the raw state fields the JS renderer consumes (board, color, env_id)
  <n>.svg   pgx's own SVG for that exact state (the ground truth)

It also (re)generates web/chess_pieces.mjs by base64-encoding pgx's bundled
chess piece SVGs, so the JS chess renderer embeds byte-identical piece art.

Run from the mcts project:  uv run python web/gen_reference.py
"""

import base64
import json
import os

import jax
import jax.numpy as jnp
import pgx
from pgx._src.visualizer import Visualizer

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.abspath(os.path.join(HERE, "..", ".."))
OUT = os.path.join(HERE, "reference")

PGX_CHESS_IMG = os.path.join(
    os.path.dirname(pgx.__file__), "_src", "dwg", "images", "chess"
)
# token used by pgx's chess renderer -> its asset filename
PIECE_FILES = {
    "wP": "wPawn", "wN": "wKnight", "wB": "wBishop",
    "wR": "wRook", "wQ": "wQueen", "wK": "wKing",
    "P": "bPawn", "N": "bKnight", "B": "bBishop",
    "R": "bRook", "Q": "bQueen", "K": "bKing",
}


def pgx_svg(state):
    # color_theme="light" matches what we render on the (light) site card
    return Visualizer(color_theme="light").get_dwg(states=state).tostring()


def state_record(state):
    rec = {"env_id": state.env_id,
           "board": [int(x) for x in state._x.board.reshape(-1)]}
    if hasattr(state._x, "color"):
        rec["color"] = int(state._x.color)
    return rec


def play(env_id, seed, want_indices):
    """Roll out random legal moves; return states at the requested move counts."""
    env = pgx.make(env_id)
    step = jax.jit(env.step)
    key = jax.random.PRNGKey(seed)
    key, sub = jax.random.split(key)
    state = env.init(sub)
    seq = [state]
    for _ in range(max(want_indices)):
        if bool(state.terminated | state.truncated):
            break
        key, sub = jax.random.split(key)
        legal = jnp.where(state.legal_action_mask)[0]
        a = legal[jax.random.randint(sub, (), 0, legal.shape[0])]
        state = step(state, a)
        seq.append(state)
    return [seq[min(i, len(seq) - 1)] for i in want_indices]


def dump(game, states):
    d = os.path.join(OUT, game)
    os.makedirs(d, exist_ok=True)
    n_board = 0
    for n, s in enumerate(states):
        rec = state_record(s)
        n_board = len(rec["board"])
        with open(os.path.join(d, f"{n}.json"), "w") as f:
            json.dump(rec, f)
        with open(os.path.join(d, f"{n}.svg"), "w") as f:
            f.write(pgx_svg(s))
    print(f"  {game}: {len(states)} states (board len {n_board})")


def gen_chess_pieces():
    entries = []
    for token, name in PIECE_FILES.items():
        with open(os.path.join(PGX_CHESS_IMG, f"{name}.svg"), "rb") as f:
            b64 = base64.b64encode(f.read()).decode("ascii")
        entries.append(f'  {json.dumps(token)}: "data:image/svg+xml;base64,{b64}",')
    body = "\n".join(entries)
    out = os.path.join(SITE, "assets", "js", "mcts", "chess_pieces.mjs")
    with open(out, "w") as f:
        f.write(
            "// Auto-generated by web/gen_reference.py from pgx's bundled chess\n"
            "// piece SVGs (Cburnett set). Do not edit by hand.\n"
            "export const CHESS_PIECES = {\n" + body + "\n};\n"
        )
    print(f"  wrote chess_pieces.mjs ({len(PIECE_FILES)} pieces)")


def main():
    os.makedirs(OUT, exist_ok=True)
    print("generating reference fixtures:")
    dump("tic_tac_toe", play("tic_tac_toe", 0, [0, 3, 5, 7]))
    dump("connect_four", play("connect_four", 1, [0, 4, 10, 20]))
    # chess: include odd move counts so a black-to-move (flipped) state is covered
    dump("chess", play("chess", 2, [0, 1, 4, 7]))
    gen_chess_pieces()
    print("done ->", OUT)


if __name__ == "__main__":
    main()
